# Generated by Django 5.2.2 on 2026-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Компанія')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('consultation', 'Консультація'), ('order', 'Замовлення'), ('service', 'Сервіс'), ('other', 'Інше')], default='consultation', max_length=20, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
                'ordering': ['-created_at'],
            },
        ),
    ]
