# Generated by Django 5.2.2 on 2026-06-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(choices=[('embossing', 'Вали тиснення'), ('anilox', 'Анілоксові вали та формні гільзи'), ('equipment', 'Обладнання та комплектуючи'), ('other', 'Інше / загальна консультація')], default='embossing', max_length=20, verbose_name='Категорія продукту'),
        ),
    ]
