# Generated by Django 5.1.15 on 2026-06-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/gallery/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Фото категорії',
                'verbose_name_plural': 'Фото категорії',
                'ordering': ['order'],
            },
        ),
    ]
