# Generated by Django 5.2.2 on 2026-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Підпис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографії',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('embed_url', models.URLField(blank=True, verbose_name='Посилання (YouTube embed)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Відео файл')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='gallery/posters/', verbose_name='Постер')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Відео',
                'verbose_name_plural': 'Відео',
                'ordering': ['order'],
            },
        ),
    ]
