# Generated by Django 5.2.2 on 2026-06-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('file', models.FileField(upload_to='documents/', verbose_name='PDF файл')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи (E-Catalog)',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
