# Generated by Django 5.2.2 on 2026-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nikola', max_length=120, verbose_name='Назва сайту')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Слоган')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hero зображення')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=100, verbose_name='Hero eyebrow текст')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Hero заголовок')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Hero підзаголовок')),
                ('about_text', models.TextField(blank=True, verbose_name='Про компанію')),
                ('clients_text', models.TextField(blank=True, verbose_name='Клієнтська база')),
                ('phone', models.CharField(blank=True, default='+38 (066) 988-3242', max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='nikolajcornejko@gmail.com', max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Робочі години')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
