# Generated by Django 5.1.15 on 2026-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='+38 (066) 988-32-42', max_length=30, verbose_name='Телефон'),
        ),
    ]
