# Generated by Django 5.2.2 on 2026-06-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=50, verbose_name='Артикль')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price_note', models.CharField(blank=True, default='За запитом', max_length=100, verbose_name='Ціна (примітка)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Позиція прайсу',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
